//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PYATAYALABA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Balance
    {
        public int Id { get; set; }
        public string Summa { get; set; }
        public string NumberCard { get; set; }
    
        public virtual UserData UserData { get; set; }
    }
}
